version: '3'
services:
  ranger-hive:
    build:
      context: .
      dockerfile: Dockerfile.ranger-hive
      args:
        - HIVE_HADOOP_VERSION=${HIVE_HADOOP_VERSION}
        - HIVE_VERSION=${HIVE_VERSION}
        - HIVE_PLUGIN_VERSION=${HIVE_PLUGIN_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
    image: ranger-hive
    container_name: ranger-hive
    hostname: ranger-hive.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "10000:10000"
      - "9083:9083"
    depends_on:
      ranger:
        condition: service_started
      ranger-zk:
        condition: service_started
    environment:
      - HIVE_HADOOP_VERSION
      - HIVE_VERSION
      - HIVE_PLUGIN_VERSION
      - RANGER_DB_TYPE
      - IS_RESUME=true

networks:
  ranger:
    name: rangernw
  common-network:
    driver: overlay

